### PR TITLE
~25% speedup in lisp code

### PR DESCRIPTION
**Pull request by guicho271828**
mainly due to reducing the memory usage and increasing the cache locality

### CODE REVIEW

**Comment by guicho271828** [comment]
https://www.reddit.com/r/lisp/comments/pctjh9/optimizing_a_path_tracer/

**Comment by guicho271828** [comment]
C version ~ 20 seconds,
Lisp version ~ 43 seconds, improved from 60~70 seconds

**Comment by niofis** [comment]
Thank you so much for updating this implementation, it really needs this kind of improvements.

**Comment by guicho271828** [comment]
please consider updating the runtime in readme

**Comment by bpecsek** [comment]
Please note that we might not see such a major speedup if the code is run on the old Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz CPU.
On my CPU (i7-7700HQ) your code runs in 59 sec. C runs in 17 sec.
The one I've just PR-ed improves it by another 12% (on my CPU) and runs in 52 sec.
We have to wait and see how they perform on the actual CPU used for the benchmark.
If the benchmark is run on a more recent, at least Skylake, CPU then we are good if an old one SBCL might not perform that well. 

Nevertheless the site should be updated with the new numbers for sure!

**Comment by bpecsek** [comment]
Any chance to update the README.md to reflect the speeds of the PR-ed lisp codes?

**Pull request merged**
